---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    service_list:
      - name: simple-service
      # Don't know how to make a simple forking service.
      # - name: forking-service
      - name: specific-stop-service
      - name: specific-user-group-service
      - name: specific-workingdirectory-service
      - name: specific-pattern-service

  tasks:
    - name: start {{ item.name }}
      service:
        name: "{{ item.name }}"
        state: started
      with_items:
        - "{{ service_list }}"

    - name: stop {{ item.name }}
      service:
        name: "{{ item.name }}"
        state: stopped
      with_items:
        - "{{ service_list }}"
